title: ALLHARDWORK.CLUB
logo: /logo-1.png
description: ALLHARDWORK.CLUB is for people with NO TALENT, doing WHATEVER IT TAKES, and trying to FIND A WAY to accomplish the impossible. Founded by Matt Mcelroy and Morgan Pearson, ALLHARDWORK.CLUB will chronicle their journey to the Olympics and beyond.
theme: jekyll-theme-minimal
